name: Execute Docker commands

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute Docker commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.GH_TOKEN }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull dockernode
            docker run -d -p 3002:3002 dockernode

