 name: Execute Docker commands
 uses: appleboy/ssh-action@master
 with:
    host: ${{ secrets.EC2_PUBLIC_IP }}
    username: ec2-user
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      docker pull dockernode
      docker run -d -p 3002:3002 dockernode

